### ISSUE TITLE
Missing cursor : pointer

### ISSUE THREAD

**Issue by rohitmore07** [prazzon/Flexbox-Labs#4]
The logo and name in the navbar are currently static, not clickable and lack a pointer cursor. To improve navigation and indicate interactivity, clicking on the logo or Flexbox Labs name in the navbar should redirect users to the homepage, with a cursor pointer to signify that these elements are clickable.

**Suggested Solution :**

- Make both the logo and name clickable, linking them to the homepage route.
- Add cursor : pointer styling to both elements to indicate interactivity.

**Additional Context :**
Implementing these changes would enhance user experience by making navigation more intuitive and providing visual feedback on hover.

**Comment by prazzon** [comment]
Thank you for your feedback!

I appreciate your suggestion for enhancing the logo's interactivity. Currently, Flexbox Labs is a static app with no additional routes for navigation. However, I agree that making the logo clickable is a good improvement to future-proof the app, should more routes be added later on. I’ll add this change along with the cursor styling for a more intuitive user experience.

Thanks again for the input!
