### ISSUE TITLE
Masonry layout gap issue

### ISSUE THREAD

**Issue by theaminuli** [prazzon/Flexbox-Labs#5]
You see a screenshot
![image](https://github.com/user-attachments/assets/7054caeb-542c-4bdd-b1dc-60c473b524c7)

**Comment by prazzon** [comment]
Thanks for the feedback!

Currently, the masonry layout is optimized for column-based flex directions. Changing the direction to row or row-reverse will indeed cause misalignment.

However, a new masonry layout for row-based flex directions will be added in the next update.

Thanks again for your input—it’s greatly appreciated!
