### ISSUE TITLE
[FEAT] make the layout preview areas resizable!

### ISSUE THREAD

**Issue by Hussseinkizz** [prazzon/Flexbox-Labs#7]
thanks for the good work, but I think it would really be very helpful if the layout preview area or container was draggable and resizeable so that I can see how the flex would be like for different screens, and responsiveness!

**Comment by prazzon** [comment]
Thanks for the suggestion. It’s a fantastic idea and would definitely improve the usability of the tool. However, I’d like to gather more input on the best way to implement it without affecting the UI or functionality negatively.

For example, should the layout preview area be resizable while keeping the editor on the left a fixed width? This might leave blank spaces on either side of the preview. Alternatively, if resizing the preview also resizes the editor, it could lead to the editor becoming too wide or too narrow, and there might still be blank spaces below the preview area.

I’d love to hear your thoughts or suggestions on how to approach this implementation effectively. Thanks again

**Comment by Hussseinkizz** [comment]
![8a42f761-107d-4804-99a8-25b840331896](https://github.com/user-attachments/assets/274e46b8-3044-41b3-8eab-99bef8ca76fb)
the red marking can be where one grabs to resize, the yeah I'd go for empty space around the preview area, this how even most component libs show responsiveness for different blocks...

**Comment by prazzon** [comment]
Took a while, but feature implemented and pushed! Thanks for the suggestion.

**Comment by Hussseinkizz** [comment]
> Took a while, but feature implemented and pushed! Thanks for the suggestion.

Sure let me check it out, thanks for listening!
