### ISSUE TITLE
[FEAT] Export As HTML Document

### ISSUE THREAD

**Issue by Nathan-Somto** [prazzon/Flexbox-Labs#8]
The project is really cool! I think it would be great to add an option to export the generated code as a `.html` file since the current implementation only saves the code in local storage. This would reduce the steps needed to visualize the code locally, as the current setup requires copying twice. What do you think?

**Comment by prazzon** [comment]
Thanks for your feedback! I'll look into implementing this

**Comment by prazzon** [comment]
Feature implemented and pushed! Thanks for your suggestion.
